<template>
  <div class="columns is-centered">
    <div class="column form-col is-half">
      <form action="/" class="form" autocomplete="off">
        <div class="field">
          <label class="label">User's Token <a class="form_help" href="https://id.atlassian.com/manage/api-tokens?_ga=2.83521503.892353958.1532003274-1217404211.1532003274" target="_blank">Click Here</a></label>
          <div class="control has-icons-left">
            <input class="input" type="text" name="jira_token" placeholder="Please enter the user's token generated by the link above" v-model="token" @blur="$v.token.$touch()" :class="{'is-danger' : $v.token.$error}">
            <span class="icon is-small is-left">
              <i class="fas fa-key"></i>
            </span>
          </div>
        </div>
        <div class="field">
          <label class="label">User's Email</label>
          <div class="control has-icons-left">
            <input class="input" type="email" name="jira_email" placeholder="Please enter the user's email or username" v-model="email" @blur="$v.email.$touch()" :class="{'is-danger' : $v.email.$error}">
            <span class="icon is-small is-left">
              <i class="fas fa-envelope"></i>
            </span>
          </div>
        </div>
        <div class="field">
          <label class="label">Site's Name</label>
          <div class="control has-icons-left">
            <input class="input" type="text" name="jira_domain" placeholder="Please enter the sites name ex. your-site.atlassian.net" v-model="site" @blur="$v.site.$touch()" :class="{'is-danger' : $v.site.$error}">
            <span class="icon is-small is-left">
              <i class="fas fa-cloud"></i>
            </span>
          </div>
        </div>
        <div class="field">
          <label class="label">Project's Key <a class="form_help" id="jira_help" href='#' @click.prevent="show = true">Need Help ?</a></label>
          <div class="control has-icons-left">
            <input class="input" type="text" name="jira_project_key" placeholder="Please enter your project's key or id" v-model="key" @blur="$v.key.$touch()" :class="{'is-danger' : $v.key.$error}">
            <span class="icon is-small is-left">
              <i class="fas fa-key"></i>
            </span>
          </div>
        </div>
        <label class="laber">Choose the fields you want to get:</label>
        <div id="checkboxes" :class="{error: $v.fields.$error}">
          <div>
              <input type="checkbox" id="jira_issues" name="fields"
                     value="issues" v-model="fields" checked @change="$v.fields.$touch()" :class="{'is-danger' : $v.fields.$error}" />
              <label for="jira_issues">Issues</label>
          </div>
          <div>
              <input type="checkbox" id="jira_users" name="fields"
                     value="users" v-model="fields" @change="$v.fields.$touch()" :class="{'is-danger' : $v.fields.$error}"  />
              <label for="jira_users">Users</label>
          </div>
        </div>
        <div class="field is-grouped">
          <div class="control">
            <button class="button is-primary" type="submit" @click.prevent="submit">Submit</button>
          </div>
          <div class="control">
            <button class="button is-danger" type="reset">Reset</button>
          </div>
        </div>
        <app-errors @deleteErrors="errors = $event" :errorText="errorText" v-if="errors"></app-errors>
      </form>
      <app-modal v-if="show" @closeModal="show = false"></app-modal>
      <app-result v-if="result" :results="results" @hide="result = $event"></app-result>
    </div>
  </div>
</template>

<script>
  import JiraModal from './modals/JiraModal.vue';
  import Result from './../Result.vue';
  import Errors from './../Errors.vue';
  import axios from 'axios';
  import {required} from 'vuelidate/lib/validators';

  export default {
    data(){
      return {
        token: '',
        email: '',
        key: '',
        site: '',
        fields: ['issues'],
        show: false,
        errors: false,
        errorText: '',
        result: false,
        results: null
      }
    },
    validations: {
      token: { required },
      email: {required},
      key: {required},
      site: {required},
      fields: {required}
    },
    components: {
      appResult: Result,
      appModal: JiraModal,
      appErrors: Errors,
    },
    props:['server'],
    methods: {
      submit(){
        this.result = false;
        this.errors = false;
        if (this.checkErrors()) {
          this.errorText = 'Please complete the form correctly !';
          return this.errors = true;
        }
        axios.get(this.server+'/api/jira/project/'+this.key+'?token='+this.token+'&fields='+this.fields.join()+"&email="+this.email+"&domain="+this.site)
        .then(response =>{
          this.results = response.data;
          if (this.results.errorBoolean) {
            this.errorText = this.results.messages[0];
            return this.errors = true;
          }
          this.result = true;
        })
        .catch(error => {
          this.errorText = 'Ooops something went wrong while connecting to the server !';
          return this.errors = true;
        });
      },
      checkErrors(){
        if (this.$v.token.$invalid || this.$v.email.$invalid || this.$v.fields.$invalid || this.$v.key.$invalid || this.$v.site.$invalid) {
          return true
        }else{
          return false;
        }
      }
    }
  }
</script>

<style scoped>
</style>
