<template>
  <div class="columns is-centered">
    <div class="column form-col is-half">
      <form action="/" class="form" autocomplete="off">
        <div class="field">
          <label class="label">User's Token <a class="form_help" href="https://trello.com/1/authorize?key=0043dc605ec22c8b475f7e945cc1f067&scope=read%2Cwrite&name=Data+Integration+App&expiration=never&response_type=token" target="_blank">Click Here</a></label>
          <div class="control has-icons-left">
            <input class="input" type="text" name="trello_token" placeholder="Please enter the user's token generated by the link above" v-model="token" @blur="$v.token.$touch()" :class="{'is-danger' : $v.token.$error}">
            <span class="icon is-small is-left">
              <i class="fas fa-key"></i>
            </span>
          </div>
        </div>
        <div class="field">
          <label class="label">Board's Short Link <a class="form_help" id="trello_help" href='#' @click.prevent="show = true">Need Help ?</a></label>
          <div class="control has-icons-left">
            <input class="input" type="text" name="trello_short_link" placeholder="Please enter the short link of the board" v-model="shortLink" @blur="$v.shortLink.$touch()" :class="{'is-danger' : $v.shortLink.$error}">
            <span class="icon is-small is-left">
              <i class="fas fa-link"></i>
            </span>
          </div>
        </div>
        <label class="laber">Choose the fields you want to get:</label>
        <div id="checkboxes" :class="{error: $v.fields.$error}">
          <div>
              <input type="checkbox" id="trello_cards" name="fields"
                     value="cards" v-model="fields" checked @change="$v.fields.$touch()" :class="{'is-danger' : $v.fields.$error}" />
              <label for="trello_cards">Cards</label>
          </div>
          <div>
              <input type="checkbox" id="trello_lists" name="fields"
                     value="lists" v-model="fields" @change="$v.fields.$touch()" :class="{'is-danger' : $v.fields.$error}"  />
              <label for="trello_lists">Lists</label>
          </div>
          <div>
              <input type="checkbox" id="trello_checklists" name="fields"
                     value="checklists" v-model="fields" @change="$v.fields.$touch()" :class="{'is-danger' : $v.fields.$error}" />
              <label for="trello_checklists">Checklists</label>
          </div>
          <div>
              <input type="checkbox" id="trello_members" name="fields"
                     value="members" v-model="fields" @change="$v.fields.$touch()" :class="{'is-danger' : $v.fields.$error}" />
              <label for="trello_members">Members</label>
          </div>
        </div>
        <div class="field is-grouped">
          <div class="control">
            <button class="button is-primary" type="submit" @click.prevent="submit">Submit</button>
          </div>
          <div class="control">
            <button class="button is-danger" type="reset">Reset</button>
          </div>
        </div>
          <app-errors @deleteErrors="errors = $event" :errorText="errorText" v-if="errors"></app-errors>
      </form>
      <app-modal :show="show" @closeModal="show = false"></app-modal>
      <app-result v-if="result" :results="results" @hide="result = $event"></app-result>
    </div>
  </div>
</template>

<script>
  import TrelloModal from './modals/TrelloModal.vue';
  import Result from './../Result.vue';
  import Errors from './../Errors.vue';
  import axios from 'axios';
  import {required} from 'vuelidate/lib/validators';
  export default {
    data(){
      return {
        token: '',
        shortLink: '',
        fields: ['cards'],
        show: false,
        result: false,
        errors: false,
        errorText: '',
        results: null
      };
    },
    validations: {
      token: { required },
      shortLink: {required},
      fields: {required}
    },
    methods:{
      submit(){
        this.result = false;
        this.errors = false;
        if (this.checkErrors()) {
          this.errorText = 'Please complete the form correctly !';
          return this.errors = true;
        }
        axios.get(this.server+'/api/trello/board/shortlink/'+this.shortLink+'?token='+this.token+'&fields='+this.fields.join())
        .then(response =>{
          this.results = response.data;
          if (this.results.errorBoolean) {
            this.errorText = this.results.messages[0];
            return this.errors = true;
          }
          this.result = true;
        })
        .catch(error => {
          this.errorText = 'Ooops something went wrong while connecting to the server !';
          return this.errors = true;
        });
      },
      checkErrors(){
        if (this.$v.token.$invalid || this.$v.shortLink.$invalid || this.$v.fields.$invalid) {
          return true
        }else{
          return false;
        }
      }
    },
    components: {
      appModal: TrelloModal,
      appErrors: Errors,
      appResult: Result
    },
    props:['server']
  }
</script>

<style scoped>
  #checkboxes{
    padding: 6px;
  }

  .error{
    border: 1px tomato solid;
    border-radius: 5px;
  }
</style>
